#ifndef __DOTNET_CODEDINDICES_H__
#define __DOTNET_CODEDINDICES_H__

namespace PEAnalyzer
{
	struct CodedIndices
	{
		enum Value
		{
			TYPEDEFORREF,
			HASCONSTANT,
			HASCUSTOMATTRIBUTE,
			HASFIELDMARSHAL,
			HASDECLSECURITY,
			MEMBERREFPARENT,
			HASSEMANTICS,
			METHODDEFORREF,
			MEMBERFORWARDED,
			IMPLEMENTATION,
			CUSTOMATTRIBUTETYPE,
			RESOLUTIONSCOPE
		};
	};
}

#endif // __DOTNET_CODEDINDICES_H__