#ifndef __DOTNET_METADATAINCLUDES_H__
#define __DOTNET_METADATAINCLUDES_H__

#include "IncFileNm.h"

#include ASSEMBLYOSTABLE_H
#include ASSEMBLYPROCESSORTABLE_H
#include ASSEMBLYREFOSTABLE_H
#include ASSEMBLYREFPROCESSORTABLE_H
#include ASSEMBLYREFTABLE_H
#include ASSEMBLYTABLE_H
#include CLASSLAYOUTTABLE_H
#include CONSTANTTABLE_H
#include CUSTOMATTRIBUTETABLE_H
#include DECLSECURITYTABLE_H
#include EVENTMAPTABLE_H
#include EVENTTABLE_H
#include EXPORTEDTYPETABLE_H
#include FIELDLAYOUTTABLE_H
#include FIELDMARSHALTABLE_H
#include FIELDRVATABLE_H
#include FIELDTABLE_H
#include FILETABLE_H
#include IMPLMAPTABLE_H
#include INTERFACEIMPLTABLE_H
#include MANIFESTRESOURCETABLE_H
#include MEMBERREFTABLE_H
#include METHODDEFTABLE_H
#include METHODIMPLTABLE_H
#include METHODSEMANTICSTABLE_H
#include MODULEREFTABLE_H
#include MODULETABLE_H
#include NESTEDCLASSTABLE_H
#include PARAMTABLE_H
#include PROPERTYMAPTABLE_H
#include PROPERTYTABLE_H
#include STANDALONESIGTABLE_H
#include TYPEDEFTABLE_H
#include TYPEREFTABLE_H
#include TYPESPECTABLE_H

#endif // __DOTNET_METADATAINCLUDES_H__